### ISSUE TITLE
The app isn't in the repository

### ISSUE THREAD

**Issue by PotatoSoKawaii** [AIMCRYPTION/AIMCRYPTION#1]
I am new to github. Once upon a time, I went to https://github.com/aimcryption/aimcryption and that's when I saw this cool awesome shit thing and I wanted to try the app. When I click the download button, it doesn't work. Please fix this!!! I'm currently on the new Windows 2020 Pro Max
![5f1221465405d0223c3340aa69c1907de4b04941_hq](https://user-images.githubusercontent.com/73210734/97253798-04ab9e00-1848-11eb-92a1-706bedbe7613.jpg)

**Comment by AIMCRYPTION** [comment]
Issue has been solved. Kindly revert back to repository. Duhh Windows 2020 Pro Max?!?!?!?
