### ISSUE TITLE
Read

### ISSUE THREAD

**Issue by VoipSip** [AIMCRYPTION/AIMCRYPTION#2]
how i enc my script python by password and can't make anyone to run this script before create for him normal password to use or make the ip address get access from me to can using thank you

**Comment by NoahGaeta** [comment]
You can create an API for the code on the server and create a client side script that has some form of authentication. You will need the authentication to be required to be able to hit the end points of your API. Another solution, a more simple solution, if there is simply only one password needed, you could hash and compare your password with a library like bcrypt and convert your python script into an executable format. Python is not a compiled language and you can easily modify the code. Converting it to an executable format should be good enough for your use case.

**Comment by NoahGaeta** [comment]
If you want multiple solutions just have a JSON file containing a list of hashed passwords with usernames assuming this does not need to scale. Keep in mind this not secure. You can run a dictionary-attack when you have the passwords, but it is far better than nothing.

**Comment by VoipSip** [comment]
if you have skype to talk or telegram thank you
